#!/bin/sh
exec setuidgid @@USER@@ multilog @@LOGDIR@@/@@INSTANCENAME@@-web \
    -* +Web:\ * "+* - - [* +0000] \"*" @@LOGDIR@@/@@INSTANCENAME@@-web/access \
    +* -Web:\ * "-* - - [* +0000] \"*" @@LOGDIR@@/@@INSTANCENAME@@-web/error
